FROM openjdk:17-alpine
LABEL authors="zsanzharko"

ENV BOT_USERNAME $BOT_USERNAME
ENV BOT_TOKEN $BOT_TOKEN
ENV SPRING_PORT $SPRING_PORT
ENV DATASOURCE_URL $DATASOURCE_URL
ENV DATASOURCE_USERNAME $DATASOURCE_USERNAME
ENV DATASOURCE_PASSWORD $DATASOURCE_PASSWORD
ENV ANYPAY_VERIFICATION $ANYPAY_VERIFICATION

EXPOSE $SPRING_PORT
EXPOSE 3444

WORKDIR ./
COPY ./ ./

RUN ./gradlew build

CMD ["./gradlew", "bootRun"]